<!--This File Is Generated By AI-->

<script setup lang="ts">
import {onMounted, type Ref, ref} from "vue"
import NProgress from 'nprogress'
import {AnimatePresence, Motion} from "motion-v";
import api from "@/api/http.ts";
import {useToast} from "@/composables/message.ts";
import type {
    DtoCommentDto,
    DtoLocationDto,
    ResponseAdminStatusResponse,
} from "@/api/api";
import {
    AnimateIcon,
    ArrowLeft,
    CalendarDays,
    CircleCheck,
    CircleX,
    CookingPot,
    LayoutDashboard,
    LoaderCircle,
    MapPin,
    MessageSquare,
    RefreshCcw,
    ShieldCheck,
    Star,
    Users,
} from '@respeak/lucide-motion-vue'
import {useRouter} from "vue-router"

type AdminTab = 'dashboard' | 'comments' | 'locations'

interface AdminNavItem {
    key: AdminTab
    label: string
    description: string
    icon: any
}

const toast = useToast()
const router = useRouter()

const PAGE_SIZE = 10

const activeTab: Ref<AdminTab> = ref('dashboard')
const loading = ref(false)

const status: Ref<ResponseAdminStatusResponse | null> = ref(null)
const comments: Ref<DtoCommentDto[]> = ref([])
const locations: Ref<DtoLocationDto[]> = ref([])

const commentsHasNext = ref(false)
const commentsLoading = ref(false)
const commentReviewing = ref<Set<number>>(new Set())

const locationsHasNext = ref(false)
const locationsLoading = ref(false)
const locationReviewing = ref<Set<number>>(new Set())

const navItems: AdminNavItem[] = [
    {key: 'dashboard', label: '概览', description: '应用运行状态', icon: LayoutDashboard},
    {key: 'comments', label: '评论审核', description: '待审核的评论', icon: MessageSquare},
    {key: 'locations', label: '地点审核', description: '待审核的地点', icon: MapPin},
]

function formatTime(value?: string): string {
    if (!value) return "-"
    const date = new Date(value)
    if (Number.isNaN(date.getTime())) return value
    return date.toLocaleString('zh-CN', {
        year: 'numeric', month: '2-digit', day: '2-digit',
        hour: '2-digit', minute: '2-digit',
    })
}

async function loadStatus() {
    try {
        const resp = await api.admin.statusList()
        if (resp.data.code !== 0) {
            toast.error("加载状态失败: " + resp.data.message)
            return
        }
        status.value = resp.data.data ?? null
    } catch (e) {
        toast.error("加载状态失败: 服务器错误")
    }
}

async function loadComments(reset = true) {
    if (commentsLoading.value) return
    commentsLoading.value = true
    try {
        const query = reset || comments.value.length === 0
            ? {page_size: PAGE_SIZE}
            : {page_size: PAGE_SIZE, start_id: comments.value[comments.value.length - 1]?.id}
        const resp = await api.admin.commentsList(query)
        if (resp.data.code !== 0) {
            toast.error("加载评论失败: " + resp.data.message)
            return
        }
        const data = resp.data.data
        if (reset) comments.value.length = 0
        comments.value.push(...(data?.comments ?? []))
        commentsHasNext.value = data?.has_next ?? false
    } catch (e) {
        toast.error("加载评论失败: 服务器错误")
    } finally {
        commentsLoading.value = false
    }
}

async function loadLocations(reset = true) {
    if (locationsLoading.value) return
    locationsLoading.value = true
    try {
        const query = reset || locations.value.length === 0
            ? {page_size: PAGE_SIZE}
            : {page_size: PAGE_SIZE, start_id: locations.value[locations.value.length - 1]?.id}
        const resp = await api.admin.locationsList(query)
        if (resp.data.code !== 0) {
            toast.error("加载地点失败: " + resp.data.message)
            return
        }
        const data = resp.data.data
        if (reset) locations.value.length = 0
        locations.value.push(...(data?.locations ?? []))
        locationsHasNext.value = data?.has_next ?? false
    } catch (e) {
        toast.error("加载地点失败: 服务器错误")
    } finally {
        locationsLoading.value = false
    }
}

async function reviewComment(comment: DtoCommentDto, pass: boolean) {
    const id = comment.id ?? 0
    if (!id || commentReviewing.value.has(id)) return
    commentReviewing.value.add(id)
    try {
        const resp = await api.admin.commentsIdPartialUpdate(id, {pass})
        if (resp.data.code !== 0) {
            toast.error("审核失败: " + resp.data.message)
            return
        }
        toast.success(pass ? "评论已通过" : "评论已驳回")
        comments.value = comments.value.filter(c => c.id !== id)
    } catch (e) {
        toast.error("审核失败: 服务器错误")
    } finally {
        commentReviewing.value.delete(id)
    }
}

async function reviewLocation(location: DtoLocationDto, pass: boolean) {
    const id = location.id ?? 0
    if (!id || locationReviewing.value.has(id)) return
    locationReviewing.value.add(id)
    try {
        const resp = await api.admin.locationsIdPartialUpdate(id, {pass})
        if (resp.data.code !== 0) {
            toast.error("审核失败: " + resp.data.message)
            return
        }
        toast.success(pass ? "地点已通过" : "地点已驳回")
        locations.value = locations.value.filter(l => l.id !== id)
    } catch (e) {
        toast.error("审核失败: 服务器错误")
    } finally {
        locationReviewing.value.delete(id)
    }
}

async function onRefresh() {
    loading.value = true
    if (activeTab.value === 'dashboard') await loadStatus()
    else if (activeTab.value === 'comments') await loadComments(true)
    else await loadLocations(true)
    loading.value = false
}

function switchTab(tab: AdminTab) {
    activeTab.value = tab
}

onMounted(async () => {
    NProgress.done()
    await Promise.all([loadStatus(), loadComments(true), loadLocations(true)])
})
</script>

<template>
    <div class="relative flex h-full w-full bg-blue-50">
        <aside class="flex w-64 shrink-0 flex-col border-r border-gray-100 bg-white shadow-2xl">
            <div class="flex items-center gap-3 px-5 py-6">
                <div class="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-400 shadow">
                    <AnimateIcon animateOnHover triggerTarget="parent">
                        <ShieldCheck class="text-white" :size="24"/>
                    </AnimateIcon>
                </div>
                <div class="flex flex-col leading-tight">
                    <span class="text-lg font-bold text-gray-800">管理后台</span>
                    <span class="text-xs text-gray-400">RiceRise Admin</span>
                </div>
            </div>

            <nav class="flex flex-col space-y-1 px-3">
                <button
                    v-for="item in navItems"
                    :key="item.key"
                    @click="switchTab(item.key)"
                    class="group flex items-center gap-3 rounded-2xl px-3 py-3 text-left transition-colors"
                    :class="activeTab === item.key
                        ? 'bg-blue-400 text-white shadow'
                        : 'text-gray-600 hover:bg-blue-50 hover:text-blue-500'"
                >
                    <AnimateIcon animateOnHover triggerTarget="parent">
                        <component :is="item.icon" :size="20"/>
                    </AnimateIcon>
                    <span class="flex flex-col">
                        <span class="font-medium">{{ item.label }}</span>
                        <span
                            class="text-xs"
                            :class="activeTab === item.key ? 'text-blue-50' : 'text-gray-400'"
                        >{{ item.description }}</span>
                    </span>
                </button>
            </nav>

            <div class="mt-auto p-3">
                <button
                    @click="async () => await router.replace({name: 'home'})"
                    class="flex w-full items-center justify-center gap-2 rounded-2xl border border-gray-200 px-3 py-3 text-gray-600 transition-colors hover:bg-blue-400 hover:text-white"
                >
                    <AnimateIcon animateOnHover triggerTarget="parent">
                        <ArrowLeft :size="18"/>
                    </AnimateIcon>
                    返回主页
                </button>
            </div>
        </aside>

        <main class="relative flex-1 overflow-hidden">
            <header class="flex items-center justify-between px-8 py-6">
                <div class="flex flex-col">
                    <h1 class="text-2xl font-bold text-gray-800">
                        {{ navItems.find(i => i.key === activeTab)?.label }}
                    </h1>
                    <span class="text-sm text-gray-500">
                        {{ navItems.find(i => i.key === activeTab)?.description }}
                    </span>
                </div>
                <button
                    @click="onRefresh"
                    class="flex h-11 w-11 items-center justify-center rounded-full bg-white text-gray-500 shadow transition-colors hover:bg-blue-400 hover:text-white"
                >
                    <AnimateIcon animateOnHover triggerTarget="parent">
                        <RefreshCcw :size="20" :class="{'animate-spin': loading}"/>
                    </AnimateIcon>
                </button>
            </header>

            <section class="h-[calc(100%-6rem)] overflow-y-auto px-8 pb-8">
                <AnimatePresence mode="wait">
                    <Motion
                        :key="activeTab"
                        :initial="{opacity: 0, y: 12}"
                        :animate="{opacity: 1, y: 0}"
                        :exit="{opacity: 0, y: -12}"
                        :transition="{duration: 0.2, ease: 'easeOut'}"
                        class="h-full"
                    >
                        <template v-if="activeTab === 'dashboard'">
                            <div class="grid grid-cols-2 gap-5 xl:grid-cols-4">
                                <div class="flex flex-col rounded-2xl bg-white p-5 shadow-lg">
                                    <div class="flex items-center justify-between">
                                        <span class="text-sm text-gray-500">总用户数</span>
                                        <Users class="text-blue-400" :size="20"/>
                                    </div>
                                    <span class="mt-2 text-3xl font-bold text-gray-800">{{ status?.total_user ?? '-' }}</span>
                                </div>
                                <div class="flex flex-col rounded-2xl bg-white p-5 shadow-lg">
                                    <div class="flex items-center justify-between">
                                        <span class="text-sm text-gray-500">总地点数</span>
                                        <MapPin class="text-blue-400" :size="20"/>
                                    </div>
                                    <span class="mt-2 text-3xl font-bold text-gray-800">{{ status?.total_location ?? '-' }}</span>
                                </div>
                                <div class="flex flex-col rounded-2xl bg-white p-5 shadow-lg">
                                    <div class="flex items-center justify-between">
                                        <span class="text-sm text-gray-500">总饭局数</span>
                                        <CalendarDays class="text-blue-400" :size="20"/>
                                    </div>
                                    <span class="mt-2 text-3xl font-bold text-gray-800">{{ status?.total_dinner ?? '-' }}</span>
                                </div>
                                <div class="flex flex-col rounded-2xl bg-white p-5 shadow-lg">
                                    <div class="flex items-center justify-between">
                                        <span class="text-sm text-gray-500">进行中饭局</span>
                                        <CookingPot class="text-blue-400" :size="20"/>
                                    </div>
                                    <span class="mt-2 text-3xl font-bold text-gray-800">{{ status?.current_dinner ?? '-' }}</span>
                                </div>
                            </div>

                            <div class="mt-5 grid grid-cols-2 gap-5">
                                <div class="flex flex-col rounded-2xl bg-white p-6 shadow-lg">
                                    <h2 class="text-lg font-bold text-gray-800">待审核评论</h2>
                                    <p class="mt-1 text-sm text-gray-500">{{ comments.length }} 条待处理</p>
                                    <button
                                        @click="switchTab('comments')"
                                        class="mt-4 self-start rounded-lg border border-gray-200 px-4 py-2 text-sm transition-colors hover:bg-blue-400 hover:text-white"
                                    >前往审核</button>
                                </div>
                                <div class="flex flex-col rounded-2xl bg-white p-6 shadow-lg">
                                    <h2 class="text-lg font-bold text-gray-800">待审核地点</h2>
                                    <p class="mt-1 text-sm text-gray-500">{{ locations.length }} 个待处理</p>
                                    <button
                                        @click="switchTab('locations')"
                                        class="mt-4 self-start rounded-lg border border-gray-200 px-4 py-2 text-sm transition-colors hover:bg-blue-400 hover:text-white"
                                    >前往审核</button>
                                </div>
                            </div>
                        </template>

                        <template v-else-if="activeTab === 'comments'">
                            <div class="flex flex-col space-y-3">
                                <AnimatePresence>
                                <Motion
                                    v-for="comment in comments"
                                    :key="comment.id"
                                    layout
                                    :initial="{opacity: 0, x: 30}"
                                    :animate="{opacity: 1, x: 0}"
                                    :exit="{opacity: 0, x: -30}"
                                    :transition="{type: 'spring', stiffness: 300, damping: 30}"
                                    class="flex flex-col rounded-2xl bg-white p-5 shadow-lg"
                                >
                                    <div class="flex items-start justify-between">
                                        <div class="flex flex-col">
                                            <span class="font-bold text-gray-800">{{ comment.user?.nickname ?? '匿名用户' }}</span>
                                            <span class="text-xs text-gray-400">@ {{ comment.user?.username ?? '-' }}</span>
                                        </div>
                                        <div class="flex items-center space-x-0.5">
                                            <Star
                                                v-for="n in 5"
                                                :key="n"
                                                :size="16"
                                                :class="n <= (comment.rating ?? 0) ? 'text-yellow-400' : 'text-gray-200'"
                                                :fill="n <= (comment.rating ?? 0) ? 'currentColor' : 'none'"
                                            />
                                        </div>
                                    </div>
                                    <p class="mt-3 text-gray-700">{{ comment.content }}</p>
                                    <div class="mt-3 flex items-center gap-2 text-xs text-gray-400">
                                        <MapPin :size="14"/>
                                        <span>{{ comment.location?.name ?? '未知地点' }}</span>
                                        <span>·</span>
                                        <span>{{ formatTime(comment.createdAt) }}</span>
                                    </div>
                                    <div class="mt-4 flex space-x-2">
                                        <button
                                            @click="async () => await reviewComment(comment, true)"
                                            :disabled="commentReviewing.has(comment.id ?? 0)"
                                            class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-blue-400 py-2 text-white shadow transition-colors hover:brightness-90 disabled:opacity-50"
                                        >
                                            <AnimateIcon animateOnHover triggerTarget="parent">
                                                <CircleCheck :size="18"/>
                                            </AnimateIcon>
                                            通过
                                        </button>
                                        <button
                                            @click="async () => await reviewComment(comment, false)"
                                            :disabled="commentReviewing.has(comment.id ?? 0)"
                                            class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-white py-2 text-gray-600 shadow transition-colors hover:bg-red-400 hover:text-white disabled:opacity-50"
                                        >
                                            <AnimateIcon animateOnHover triggerTarget="parent">
                                                <CircleX :size="18"/>
                                            </AnimateIcon>
                                            驳回
                                        </button>
                                    </div>
                                </Motion>
                                </AnimatePresence>

                                <span v-if="comments.length === 0 && !commentsLoading" class="py-20 text-center text-sm text-gray-500">
                                    当前暂无待审核评论...
                                </span>
                                <button
                                    v-if="commentsHasNext"
                                    @click="loadComments(false)"
                                    :disabled="commentsLoading"
                                    class="flex items-center justify-center gap-2 rounded-2xl border border-gray-200 bg-white py-3 text-sm text-gray-600 shadow transition-colors hover:bg-blue-400 hover:text-white disabled:opacity-50"
                                >
                                    <LoaderCircle v-if="commentsLoading" class="animate-spin" :size="16"/>
                                    加载更多
                                </button>
                            </div>
                        </template>

                        <template v-else>
                            <div class="flex flex-col space-y-3">
                                <AnimatePresence>
                                <Motion
                                    v-for="location in locations"
                                    :key="location.id"
                                    layout
                                    :initial="{opacity: 0, x: 30}"
                                    :animate="{opacity: 1, x: 0}"
                                    :exit="{opacity: 0, x: -30}"
                                    :transition="{type: 'spring', stiffness: 300, damping: 30}"
                                    class="flex flex-col rounded-2xl bg-white p-5 shadow-lg"
                                >
                                    <div class="flex items-start justify-between">
                                        <div class="flex flex-col">
                                            <span class="text-lg font-bold text-gray-800">{{ location.name }}</span>
                                            <span class="text-sm text-gray-500">{{ location.address }}</span>
                                        </div>
                                        <span class="rounded-full bg-blue-50 px-3 py-1 text-xs text-blue-500">待审核</span>
                                    </div>
                                    <p class="mt-3 text-gray-700">{{ location.description }}</p>
                                    <div class="mt-3 flex items-center gap-2 text-xs text-gray-400">
                                        <MapPin :size="14"/>
                                        <span>{{ location.latitude?.toFixed(5) }}, {{ location.longitude?.toFixed(5) }}</span>
                                        <span>·</span>
                                        <span>{{ formatTime(location.createdAt) }}</span>
                                    </div>
                                    <div class="mt-4 flex space-x-2">
                                        <button
                                            @click="async () => await reviewLocation(location, true)"
                                            :disabled="locationReviewing.has(location.id ?? 0)"
                                            class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-blue-400 py-2 text-white shadow transition-colors hover:brightness-90 disabled:opacity-50"
                                        >
                                            <AnimateIcon animateOnHover triggerTarget="parent">
                                                <CircleCheck :size="18"/>
                                            </AnimateIcon>
                                            通过
                                        </button>
                                        <button
                                            @click="async () => await reviewLocation(location, false)"
                                            :disabled="locationReviewing.has(location.id ?? 0)"
                                            class="flex flex-1 items-center justify-center gap-2 rounded-lg bg-white py-2 text-gray-600 shadow transition-colors hover:bg-red-400 hover:text-white disabled:opacity-50"
                                        >
                                            <AnimateIcon animateOnHover triggerTarget="parent">
                                                <CircleX :size="18"/>
                                            </AnimateIcon>
                                            驳回
                                        </button>
                                    </div>
                                </Motion>
                                </AnimatePresence>

                                <span v-if="locations.length === 0 && !locationsLoading" class="py-20 text-center text-sm text-gray-500">
                                    当前暂无待审核地点...
                                </span>
                                <button
                                    v-if="locationsHasNext"
                                    @click="loadLocations(false)"
                                    :disabled="locationsLoading"
                                    class="flex items-center justify-center gap-2 rounded-2xl border border-gray-200 bg-white py-3 text-sm text-gray-600 shadow transition-colors hover:bg-blue-400 hover:text-white disabled:opacity-50"
                                >
                                    <LoaderCircle v-if="locationsLoading" class="animate-spin" :size="16"/>
                                    加载更多
                                </button>
                            </div>
                        </template>
                    </Motion>
                </AnimatePresence>
            </section>
        </main>
    </div>
</template>
